config/routes.rb
BillscubaCom::Application.routes.draw do
  resources :factors_users

  resources :users

  resources :factors_locations

  resources :factors

  resources :locations

  resources :site_configs

  resources :pages

  match "/", :controller => "pages", :action => "show", :id => 1

end

app/models/factors_user.rb
class FactorsUser < ActiveRecord::Base
  attr_accessible :description, :factor_id, :user_id, :value
end

app/controllers/factors_users_controller.rb
class FactorsUsersController < ApplicationController
  # GET /factors_users
  # GET /factors_users.json
  def index
    @factors_users = FactorsUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factors_users }
    end
  end

  # GET /factors_users/1
  # GET /factors_users/1.json
  def show
    @factors_user = FactorsUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factors_user }
    end
  end

  # GET /factors_users/new
  # GET /factors_users/new.json
  def new
    @factors_user = FactorsUser.new
    
    if (params.has_key? :factor_id and params[:factor_id].to_i > 0)
      this_factor = Factor.where("id >= #{params[:factor_id]} and show_in_survey = true").order("id asc").first
    else
      this_factor = Factor.first
    end
    
    if this_factor.present?
      @factor_id = this_factor.id
    else 
      respond_to do |format|
        format.html { redirect_to "/factors_users", notice: 'Survey completed.' and return }
      end
    end    

    @user_id = User.last.id
    #@last_factors_user_id = FactorsUser.last.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factors_user }
    end
  end

  # GET /factors_users/1/edit
  def edit
    @factors_user = FactorsUser.find(params[:id])
    #@last_factors_user_id = FactorsUser.last.id
  end

  # POST /factors_users
  # POST /factors_users.json
  def create
    @factors_user = FactorsUser.new(params[:factors_user])

    respond_to do |format|
      if @factors_user.save
        format.html { redirect_to "/factors_users/new?factor_id=#{@factors_user.factor_id + 1}", notice: 'Factors user was successfully created.' }
        format.json { render json: @factors_user, status: :created, location: @factors_user }
      else
        format.html { render action: "new" }
        format.json { render json: @factors_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factors_users/1
  # PUT /factors_users/1.json
  def update
    @factors_user = FactorsUser.find(params[:id])

    respond_to do |format|
      if @factors_user.update_attributes(params[:factors_user])
        format.html { redirect_to @factors_user, notice: 'Factors user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factors_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factors_users/1
  # DELETE /factors_users/1.json
  def destroy
    @factors_user = FactorsUser.find(params[:id])
    @factors_user.destroy

    respond_to do |format|
      format.html { redirect_to factors_users_url }
      format.json { head :no_content }
    end
  end
end

app/views/factors_users/_form.html.haml
= form_for @factors_user do |f|
  .actions
    = f.submit 'Save'
  %hr

  - if @factors_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@factors_user.errors.count, "error")} prohibited this factors_user from being saved:"
      %ul
        - @factors_user.errors.full_messages.each do |msg|
          %li= msg

  #edit_cols
    #col_1_of_3
      .field
        = f.label :factor_id
        = f.select :factor_id, options_for_select(factors_for_select(), @factor_id),{}
      .field
        = f.label :user_id
        = f.select :user_id, options_for_select(users_for_select(), @user_id),{}
      .field
        =# f.label :value
        =# f.number_field :value
        =# f.radio :value
        = label_tag(:value_1, "No")
        = f.radio_button(:value, 1)
        = f.radio_button(:value, 2)
        = f.radio_button(:value, 3)
        = f.radio_button(:value, 4)
        = f.radio_button(:value, 5)
        = f.radio_button(:value, 6)
        = f.radio_button(:value, 7)
        = label_tag(:value_7, "Yes")
      .field
        = f.label :description
        = f.text_area :description

app/views/factors_users/edit.html.haml
%h1 
  Edit Survey Question

= render 'form'

=# link_to 'Previous', "/factors_users/#{@factors_user.id - 1}/edit"
=# link_to 'Next', "/factors_users/#{@factors_user.id + 1}/edit"

= link_to 'Show', @factors_user
\|
= link_to 'Back', factors_users_path

app/views/factors_users/index.html.haml
%h1 Survey Questions

%p#notice= notice

%table
  %tr
    %th Factor ID
    %th User ID
    %th Value
    %th Description
    %th

  - @factors_users.each do |factors_user|
    %tr
      %td= factors_user.factor_id
      %td= factors_user.user_id
      %td= factors_user.value
      %td= factors_user.description
      %td
        = link_to 'Show', factors_user
        \|
        = link_to 'Edit', edit_factors_user_path(factors_user)
        \|
        = link_to 'Destroy', factors_user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= button_to 'Start a new survey', new_factors_user_path, :method => :get

app/views/factors_users/new.html.haml
%h1 
  Survey

= render 'form'

=# link_to 'Previous', "/factors_users/new?factor_id=#{@factor_id - 1}"
=# link_to 'Next', "/factors_users/new?factor_id=#{@factor_id + 1}"

#footer
  %hr
  = link_to 'Back', factors_users_path

app/views/factors_users/show.html.haml
%p#notice= notice

#show_cols
  #col_1_of_3
  %p
    %b Factor:
    = @factors_user.factor_id
  %p
    %b User:
    = @factors_user.user_id
  %p
    %b Value:
    = @factors_user.value
  %p
    %b Description:
    = @factors_user.description

#footer
  %hr
  = link_to 'Edit', edit_factors_user_path(@factors_user)
  \|
  = link_to 'Back', factors_users_path