config/routes.rb
BillscubaCom::Application.routes.draw do
  resources :factors_users

  resources :users

  resources :factors_locations

  resources :factors

  resources :locations

  resources :site_configs

  resources :pages

  match "/", :controller => "pages", :action => "show", :id => 1

end

app/models/factors_location.rb
class FactorsLocation < ActiveRecord::Base
  attr_accessible :factor_id, :location_id, :value, :description
  belongs_to :factors
  belongs_to :locations
  
  # def self.search(search_params, filter_by, filter_params, sort_by, sort_order, page_number, items_per_page)
  #   @model_order_string = "\"title\" asc"
  #   if search_params.blank?
  #     @model_search_query = nil
  #   else
  #     @model_search_query = "(\"title\" ilike '%" + search_params + "%' or \"category\" ilike '%" + search_params + "%')"
  #   end
  #   super
  # end

end

app/controllers/factors_locations_controller.rb
class FactorsLocationsController < ApplicationController
  # GET /factors_locations
  # GET /factors_locations.json
  def index
    @factors_locations = FactorsLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factors_locations }
    end
  end

  # GET /factors_locations/1
  # GET /factors_locations/1.json
  def show
    @factors_location = FactorsLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factors_location }
    end
  end

  # GET /factors_locations/new
  # GET /factors_locations/new.json
  def new
    @factors_location = FactorsLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factors_location }
    end
  end

  # GET /factors_locations/1/edit
  def edit
    @factors_location = FactorsLocation.find(params[:id])
  end

  # POST /factors_locations
  # POST /factors_locations.json
  def create
    @factors_location = FactorsLocation.new(params[:factors_location])

    respond_to do |format|
      if @factors_location.save
        format.html { redirect_to @factors_location, notice: 'FactorsLocation was successfully created.' }
        format.json { render json: @factors_location, status: :created, factors_location: @factors_location }
      else
        format.html { render action: "new" }
        format.json { render json: @factors_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factors_locations/1
  # PUT /factors_locations/1.json
  def update
    @factors_location = FactorsLocation.find(params[:id])

    respond_to do |format|
      if @factors_location.update_attributes(params[:factors_location])
        format.html { redirect_to @factors_location, notice: 'FactorsLocation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factors_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factors_locations/1
  # DELETE /factors_locations/1.json
  def destroy
    @factors_location = FactorsLocation.find(params[:id])
    @factors_location.destroy

    respond_to do |format|
      format.html { redirect_to factors_locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/factors_locations_helper.rb
module FactorsLocationsHelper
end

app/views/factors_locations/_form.html.haml
= form_for @factors_location do |f|
  .actions
    = f.submit 'Save'
  %hr

  - if @factors_location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@factors_location.errors.count, "error")} prohibited this factors_location from being saved:"
      %ul
        - @factors_location.errors.full_messages.each do |msg|
          %li= msg

  #edit_cols
    #col_1_of_3
      .field
        = f.label :factor_id
        / = f.text_field :factor_id
        = f.select :factor_id, options_for_select(factors_for_select()),{}
      .field
        = f.label :location_id
        / = f.text_field :location_id
        = f.select :location_id, options_for_select(locations_for_select()),{}

      .field
        = f.label :value
        = f.text_field :value
      .field
        = f.label :description
        = f.text_area :description

app/views/factors_locations/edit.html.haml
%h1 
  Survey Data
  
= render 'form'

= link_to 'Previous', "/factors_location/#{@factors_location.id - 1}/edit"
= link_to 'Next', "/factors_location/#{@factors_location.id + 1}/edit"

#footer
  %hr
  = link_to 'Show', @factors_location
  \|
  = link_to 'Back', factors_locations_path

app/views/factors_locations/index.html.haml
%h1 Listing Factors_locations

%table
  %tr
    %th Factor ID
    %th Location ID
    %th Value
    %th Description
    %th

  - @factors_locations.each do |factors_location|
    %tr
      %td= factors_location.factor_id
      %td= factors_location.location_id
      %td= factors_location.value
      %td= factors_location.description
      %td
        = link_to 'Show', factors_location
        \|
        = link_to 'Edit', edit_factors_location_path(factors_location)
        \|
        = link_to 'Destroy', factors_location, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Factors_location', new_factors_location_path

app/views/factors_locations/new.html.haml
%h1 New factors_location

= render 'form'

#footer
  %hr
  = link_to 'Back', factors_locations_path

app/views/factors_locations/show.html.haml
%p#notice= notice

#show_cols
  #col_1_of_3
    %p
      %b Factor ID:
      = @factors_location.factor_id
    %p
      %b Location ID:
      = @factors_location.location_id
    %p
      %b Value:
      = @factors_location.value
    %p
      %b Description:
      = @factors_location.description

#footer
  %hr
  = link_to 'Edit', edit_factors_location_path(@factors_location)
  \|
  = link_to 'Back', factors_locations_path