config/routes.rb
BillscubaCom::Application.routes.draw do
  resources :factors_users

  resources :users

  resources :factors_locations

  resources :factors

  resources :locations

  resources :site_configs

  resources :pages

  match "/", :controller => "pages", :action => "show", :id => 1

end

app/models/factor.rb
class Factor < ActiveRecord::Base
  attr_accessible :title, :style, :show_in_survey
  has_many :factors_locations
  has_many :locations, :through => :factors_locations

  # def self.search(search_params, filter_by, filter_params, sort_by, sort_order, page_number, items_per_page)
  #   @model_order_string = "\"title\" asc"
  #   if search_params.blank?
  #     @model_search_query = nil
  #   else
  #     @model_search_query = "(\"title\" ilike '%" + search_params + "%' or \"category\" ilike '%" + search_params + "%')"
  #   end
  #   super
  # end

end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController
  # GET /factors
  # GET /factors.json
  def index
    @factors = Factor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factors }
    end
  end

  # GET /factors/1
  # GET /factors/1.json
  def show
    @factor = Factor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factor }
    end
  end

  # GET /factors/new
  # GET /factors/new.json
  def new
    @factor = Factor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factor }
    end
  end

  # GET /factors/1/edit
  def edit
    @factor = Factor.find(params[:id])
  end

  # POST /factors
  # POST /factors.json
  def create
    @factor = Factor.new(params[:factor])

    respond_to do |format|
      if @factor.save
        format.html { redirect_to @factor, notice: 'Factor was successfully created.' }
        format.json { render json: @factor, status: :created, factor: @factor }
      else
        format.html { render action: "new" }
        format.json { render json: @factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factors/1
  # PUT /factors/1.json
  def update
    @factor = Factor.find(params[:id])

    respond_to do |format|
      if @factor.update_attributes(params[:factor])
        format.html { redirect_to @factor, notice: 'Factor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factors/1
  # DELETE /factors/1.json
  def destroy
    @factor = Factor.find(params[:id])
    @factor.destroy

    respond_to do |format|
      format.html { redirect_to factors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/_form.html.haml
= form_for @factor do |f|
  .actions
    = f.submit 'Save'
  %hr

  - if @factor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@factor.errors.count, "error")} prohibited this factor from being saved:"
      %ul
        - @factor.errors.full_messages.each do |msg|
          %li= msg
  
  #edit_cols
    #col_1_of_3
      .field
        = f.label :title
        = f.text_field :title
      .field
        = f.label :style
        / = f.text_field :style
        = f.select :style, options_for_select(styles_for_select()),{}
      .field
        = f.check_box :show_in_survey, :id => 'form_show_in_survey', :placeholder => 'Show in survey'
        = f.label :show_in_survey

    

app/views/factors/edit.html.haml
%h3 
  Editing factor:
  %i= @factor.title

= render 'form'

#footer
  %hr
  = link_to 'Show', @factor
  \|
  = link_to 'Back', factors_path

app/views/factors/index.html.haml
%h1 Listing factors

%table
  %tr
    %th Title
    %th Style
    %th Show In Survey
    %th

  - @factors.each do |factor|
    %tr
      %td= link_to factor.title, factor
      %td= factor.style
      %td= factor.show_in_survey
      %td
        = link_to 'Show', factor
        \|
        = link_to 'Edit', edit_factor_path(factor)
        \|
        = link_to 'Destroy', factor, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Factor', new_factor_path

app/views/factors/new.html.haml
%h1 New factor

= render 'form'

#footer
  %hr
  = link_to 'Back', factors_path

app/views/factors/show.html.haml
%h4
  Factor:
  = '"' + @factor.title + '"'

%p#notice= notice

#show_cols
  #col_1_of_3
    %p
      %b Title:
      = @factor.title
    %p
      %b Style:
      = @factor.style
    %p
      %b Show in Survey:
      = @factor.show_in_survey

#footer
  %hr
  = link_to 'Edit', edit_factor_path(@factor)
  \|
  = link_to 'Back', factors_path